import manifest from "@/data/page-sources.generated.json";

// Per-page "Sources" section, driven by the network claims ledger.
// The manifest is generated by docs/claims/gen-sources.mjs — do not hand-edit it.
// Renders nothing for routes with no ledger-verified claims.

type SourceClaim = { id: string; claim: string; status: string; sources: string[] };

const ROUTES = (manifest.routes ?? {}) as Record<string, SourceClaim[]>;
const SITE_ORIGIN = "https://pledgemeaning.com";

function sourceLabel(url: string): string {
  try {
    const u = new URL(url);
    if (u.hostname.startsWith("support.")) return "RSI Support";
    if (u.hostname.includes("gamespress")) return "CIG Press Release";
    if (u.hostname.includes("robertsspaceindustries")) {
      if (u.pathname.includes("/comm-link/")) return "RSI Comm-Link";
      if (u.pathname.includes("referral-program")) return "RSI Referral Program";
      if (u.pathname.includes("game-packages")) return "RSI Game Packages";
      if (u.pathname.includes("funding")) return "RSI Funding Tracker";
      if (u.pathname.includes("squadron42")) return "RSI — Squadron 42";
      return "RSI Official";
    }
    return u.hostname.replace(/^www\./, "");
  } catch {
    return "Source";
  }
}

export default function PageSources({ route }: { route: string }) {
  const claims = ROUTES[route];
  if (!claims || claims.length === 0) return null;

  const canonical = route === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${route}`;
  const citationUrls = Array.from(new Set(claims.flatMap((c) => c.sources)));
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": canonical,
    url: canonical,
    citation: citationUrls.map((url) => ({ "@type": "CreativeWork", url })),
  };

  return (
    <section className="mb-16" aria-labelledby="page-sources-heading">
      <h2 id="page-sources-heading" className="text-2xl font-bold text-cream mb-3">
        Sources
      </h2>
      <p className="text-muted text-sm leading-relaxed mb-6">
        Every factual claim on this page is verified against official Cloud Imperium Games
        sources. Figures are checked against the primary RSI page linked below — not
        third-party trackers.
      </p>
      <ul className="space-y-4">
        {claims.map((c) => (
          <li key={c.id} className="bg-midnight-mid border border-amber/20 rounded-xl p-5">
            <p className="text-cream text-sm leading-relaxed">{c.claim}</p>
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1">
              {c.sources.map((url) => (
                <a
                  key={url}
                  href={url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-mono text-xs text-amber hover:underline"
                >
                  {sourceLabel(url)} ↗
                </a>
              ))}
            </div>
          </li>
        ))}
      </ul>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </section>
  );
}
